name: Pester Tests

on:
  push:
    branches:
      - main   # Trigger when you push to the main branch
  pull_request:
    branches:
      - main   # Trigger for pull requests targeting the main branch

jobs:
  pester-tests:
    runs-on: windows-latest   # GitHub will run on a Windows machine

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up PowerShell
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    # Install Pester module
    - name: Install Pester module
      run: |
        Install-Module -Name Pester -Force -Scope CurrentUser

    # Run the Pester tests
    - name: Run Pester Tests
      run: |
        Invoke-Pester -Path C:\Users\susil\Desktop\mausam\powershell .\PesterApiCheck.tests.ps1
