name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Buildx for multi-platform builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use your Docker Hub password or access token

      - name: Build and Push Docker Image
        run: |
          docker build -t mausam868/playwright-python-tests:latest .  # Build the image
          docker push mausam868/playwright-python-tests:latest  # Push the image to Docker Hub
